FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY parser.py importer.py export_csv.py api.py ./

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
